kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-rhtap-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhtap-chatbot-app
  template:
    metadata:
      labels:
        app: rhtap-chatbot-app
    spec:
      containers:
        - name: my-rhtap-chatbot
          image: chatbot-image:latest
          ports:
            - name: http
              containerPort: 8501
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-rhtap-chatbot
spec:
  ports:
    - name: http-8501
      port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app: rhtap-chatbot-app